[pytest]
markers =
    ui: UI automation tests
    api: API automation tests
    smoke: Critical smoke tests
    regression: Full regression suite
    strict: Business critical tests

addopts = -v
filterwarnings =
    ignore::DeprecationWarning
